# Generated by Django 2.1 on 2018-10-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.DateField(verbose_name='date')),
                ('done', models.BooleanField()),
                ('expired', models.BooleanField()),
                ('title', models.CharField(max_length=1000)),
            ],
        ),
    ]
