# Generated by Django 2.1 on 2018-10-29 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20181029_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='expired',
        ),
    ]
